// Code generated by genum DO NOT EDIT.
package internal

import (
    "encoding/json"
    "fmt"
)

// IsValid has a terrible implementation, but returns true if the value is, well, valid.
func (e MyEnum2) IsValid() bool {
    _, err := e.ParseString(e.String())
    return err == nil
}

// Values returns a list of all potential values of this enum.
func (e MyEnum2) Values() []MyEnum2 {
    return []MyEnum2{
        EnumTwoValueZero,
        EnumTwoValueOne,
    }
}

// StringValues returns a list of all potential values of this enum as strings.
func (e MyEnum2) StringValues() []string {
    return []string{
        "EnumTwoValueZero",
        "EnumTwoValueOne",
    }
}

// String returns a string representation of this enum.
// Note: in the case of duplicate values only the first alphabetical definition will be choosen.
func (e MyEnum2) String() string {
    switch e {
    case EnumTwoValueZero:
        return "EnumTwoValueZero"
    case EnumTwoValueOne:
        return "EnumTwoValueOne"
    default:
        return fmt.Sprintf("UndefinedMyEnum2:%d", e)
    }
}

// ParseString will return a value as defined in string form.
func (e MyEnum2) ParseString(text string) (MyEnum2, error) {
    switch text {
    case "EnumTwoValueZero":
        return EnumTwoValueZero, nil
    case "EnumTwoValueOne":
        return EnumTwoValueOne, nil
    default:
        return 0, fmt.Errorf("`%s` is not a valid enum of type MyEnum2", text)
    }
}

// MarshalJSON implements the json.Marshaler interface for MyEnum2.
func (e MyEnum2) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MyEnum2.
func (e *MyEnum2) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
        var err error
        *e, err = MyEnum2(0).ParseString(s)
        return err
	}
	var i int
	if err := json.Unmarshal(data, &i); err == nil {
        *e = MyEnum2(i)
        if e.IsValid() {
            return nil
        }
    }

    return fmt.Errorf("unable to unmarshal MyEnum2 from `%v`", data)
}

// MarshalText implements the encoding.TextMarshaler interface for MyEnum2.
func (e MyEnum2) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MyEnum2.
func (e *MyEnum2) UnmarshalText(text []byte) error {
    var err error
	*e, err = MyEnum2(0).ParseString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for MyEnum2.
func (e MyEnum2) MarshalYAML() (any, error) {
	return e.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for MyEnum2.
func (e *MyEnum2) UnmarshalYAML(unmarshal func(any) error) error {
	var s string
	if err := unmarshal(&s); err == nil {
        var err error
        *e, err = MyEnum2(0).ParseString(s)
        return err
	}
	var i int
	if err := unmarshal(&i); err == nil {
        *e = MyEnum2(i)
        if e.IsValid() {
            return nil
        }
    }

    return fmt.Errorf("unable to unmarshal MyEnum2 from yaml")
}