// Code generated by genum DO NOT EDIT.
package internal

import (
	"encoding/json"
	"fmt"
	"slices"
	"strconv"

	"github.com/drshriveer/gtools/genum"
	"gopkg.in/yaml.v3"
)

var _EnumerableWithParsableTraitsValues = []EnumerableWithParsableTraits{
	P1,
	P2,
	P3,
}

// AlsoSometimesNonParsable returns the enum's associated trait of the same name.
// If no trait exists for the enumeration a default value will be returned.
func (e EnumerableWithParsableTraits) AlsoSometimesNonParsable() int {
	switch e {
	case P1:
		return _AlsoSometimesNonParsable
	case P2:
		return 2
	case P3:
		return 3
	}

	return *new(int)
}

// NonParsable returns the enum's associated trait of the same name.
// If no trait exists for the enumeration a default value will be returned.
func (e EnumerableWithParsableTraits) NonParsable() string {
	switch e {
	case P1:
		return _NonParsable
	case P2:
		return "non-parsable"
	case P3:
		return "non-parsable"
	}

	return *new(string)
}

// Parsable returns the enum's associated trait of the same name.
// If no trait exists for the enumeration a default value will be returned.
func (e EnumerableWithParsableTraits) Parsable() string {
	switch e {
	case P1:
		return _Parsable
	case P2:
		return "2"
	case P3:
		return "3"
	}

	return *new(string)
}

// SometimesNonParsable returns the enum's associated trait of the same name.
// If no trait exists for the enumeration a default value will be returned.
func (e EnumerableWithParsableTraits) SometimesNonParsable() int {
	switch e {
	case P1:
		return _SometimesNonParsable
	case P2:
		return 2
	case P3:
		return 1
	}

	return *new(int)
}

// IsValid returns true if the enum value is, in fact, valid.
func (e EnumerableWithParsableTraits) IsValid() bool {
	for _, v := range _EnumerableWithParsableTraitsValues {
		if v == e {
			return true
		}
	}
	return false
}

// Values returns a list of all potential values of this enum.
func (EnumerableWithParsableTraits) Values() []EnumerableWithParsableTraits {
	return slices.Clone(_EnumerableWithParsableTraitsValues)
}

// StringValues returns a list of all potential values of this enum as strings.
// Note: This does not return duplicates.
func (EnumerableWithParsableTraits) StringValues() []string {
	return []string{
		"P1",
		"P2",
		"P3",
	}
}

// String returns a string representation of this enum.
// Note: in the case of duplicate values only the first alphabetical definition will be choosen.
func (e EnumerableWithParsableTraits) String() string {
	switch e {
	case P1:
		return "P1"
	case P2:
		return "P2"
	case P3:
		return "P3"
	default:
		return fmt.Sprintf("UndefinedEnumerableWithParsableTraits:%d", e)
	}
}

// Parse will attempt to parse the value of an enum from either its string form
// or any value of a trait flagged with the --parsableByTrait flag
func (e EnumerableWithParsableTraits) Parse(input any) (EnumerableWithParsableTraits, error) {
	switch input {
	case "P1", _AlsoSometimesNonParsable, _Parsable:
		return P1, nil
	case "P2", 2, "2":
		return P2, nil
	case "P3", 3, "3":
		return P3, nil
	default:
		return 0, fmt.Errorf("`%+v` could not be parsed to enum of type EnumerableWithParsableTraits", input)
	}
}

// ParseGeneric calls TypedEnum.Parse but returns the result
// in the generic genum.Enum interface. Which is useful when you are only able to work with
// the un-typed interface.
func (e EnumerableWithParsableTraits) ParseGeneric(input any) (genum.Enum, error) {
	return e.Parse(input)
}

// MarshalJSON implements the json.Marshaler interface for EnumerableWithParsableTraits.
func (e EnumerableWithParsableTraits) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EnumerableWithParsableTraits.
func (e *EnumerableWithParsableTraits) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		var err error
		*e, err = EnumerableWithParsableTraits(0).Parse(s)
		return err
	}
	var i int
	if err := json.Unmarshal(data, &i); err == nil {
		*e = EnumerableWithParsableTraits(i)
		if e.IsValid() {
			return nil
		}
	}

	return fmt.Errorf("unable to unmarshal EnumerableWithParsableTraits from `%v`", data)
}

// MarshalText implements the encoding.TextMarshaler interface for EnumerableWithParsableTraits.
func (e EnumerableWithParsableTraits) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EnumerableWithParsableTraits.
func (e *EnumerableWithParsableTraits) UnmarshalText(text []byte) error {
	var err error
	*e, err = EnumerableWithParsableTraits(0).Parse(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for EnumerableWithParsableTraits.
func (e EnumerableWithParsableTraits) MarshalYAML() (any, error) {
	return e.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for EnumerableWithParsableTraits.
func (e *EnumerableWithParsableTraits) UnmarshalYAML(value *yaml.Node) error {
	i, err := strconv.ParseInt(value.Value, 10, 64)
	if err == nil {
		*e = EnumerableWithParsableTraits(i)
	} else {
		*e, err = EnumerableWithParsableTraits(0).Parse(value.Value)
	}
	if err != nil {
		return err
	} else if e.IsValid() {
		return nil
	}
	return fmt.Errorf("unable to unmarshal EnumerableWithParsableTraits from yaml `%s`", value.Value)
}

// IsEnum implements an empty function required to implement Enum.
func (EnumerableWithParsableTraits) IsEnum() {}
