// Code generated by gsort DO NOT EDIT.
package gencommon

// Methods implements the sort.Sort interface for Method.
type Methods []*Method

func (ms Methods) Len() int {
	return len(ms)
}
func (ms Methods) Swap(i, j int) {
	ms[i], ms[j] = ms[j], ms[i]
}
func (ms Methods) Less(i, j int) bool {
	if ms[i].IsExported == ms[j].IsExported {
		return ms[i].Name < ms[j].Name
	}
	return ms[j].IsExported
}
