// Code generated by gsort DO NOT EDIT.
package gencommon

// Methods implements the sort.Sort interface for Method.
type Methods []*Method

func (s Methods) Len() int {
	return len(s)
}
func (s Methods) Swap(i, j int) {
	s[i], s[j] = s[j], s[i]
}
func (s Methods) Less(i, j int) bool {
	if s[i].IsExported == s[j].IsExported {
		return s[i].Name < s[j].Name
	}
	return s[j].IsExported
}
